### ISSUE TITLE
CSS nesting doesn't work on Safari

### ISSUE THREAD

**Issue by tatthien** [raphaelsalaja/sylph#2]
MacOS: 14.1.1

<img width="664" alt="Screenshot 2024-10-23 at 11 18 23" src="https://github.com/user-attachments/assets/62cc4254-f502-4beb-88ae-774da371c546">

My solution:

1. Install  `postcss-nested` plugin
2. Add `postcss-nested` to postcss config
```js
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    'postcss-nested': {}
  },
}

export default config
```

**Comment by raphaelsalaja** [comment]
Thank you for this find!
